-- EREFILL Gather Stats - Schedule C Static Tables (CORE_DATA + CORE_CONFIG)
-- PDB: EREFILL_CORE (connected via ORACLE_PDB_SID)
-- Schema: CORE_DATA, CORE_CONFIG
-- Non-partitioned tables that need gather stats every 12 hours

WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;

set time on
set timing on
set serveroutput on size unlimited
set feedback on

-- ============================================
-- CORE_DATA Schema - Non-partitioned tables (Schedule-C)
-- ============================================

-- Table 1: MFS_ETOPUP_ACCOUNT_MASTER
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_DATA'', TABNAME => ''MFS_ETOPUP_ACCOUNT_MASTER'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_DATA', TABNAME => 'MFS_ETOPUP_ACCOUNT_MASTER', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 2: MFS_ETOPUP_HINT_ANSWER_MASTER
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_DATA'', TABNAME => ''MFS_ETOPUP_HINT_ANSWER_MASTER'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_DATA', TABNAME => 'MFS_ETOPUP_HINT_ANSWER_MASTER', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 3: MFS_ETOPUP_P2P_USER_DETAILS
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_DATA'', TABNAME => ''MFS_ETOPUP_P2P_USER_DETAILS'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_DATA', TABNAME => 'MFS_ETOPUP_P2P_USER_DETAILS', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 4: MFS_NICKNAME_MDN_MAPPING
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_DATA'', TABNAME => ''MFS_NICKNAME_MDN_MAPPING'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_DATA', TABNAME => 'MFS_NICKNAME_MDN_MAPPING', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 5: MFS_P2PBLOCK_MSIDN_DETAILS
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_DATA'', TABNAME => ''MFS_P2PBLOCK_MSIDN_DETAILS'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_DATA', TABNAME => 'MFS_P2PBLOCK_MSIDN_DETAILS', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 6: MFS_P2PREQUESTED_PIN_DETAILS
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_DATA'', TABNAME => ''MFS_P2PREQUESTED_PIN_DETAILS'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_DATA', TABNAME => 'MFS_P2PREQUESTED_PIN_DETAILS', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 7: MFS_ETOPUP_LOGIN_MASTER
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_DATA'', TABNAME => ''MFS_ETOPUP_LOGIN_MASTER'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_DATA', TABNAME => 'MFS_ETOPUP_LOGIN_MASTER', CASCADE => TRUE, DEGREE => 4);
END;
/

-- ============================================
-- CORE_CONFIG Schema - Non-partitioned tables (Schedule-C)
-- ============================================

-- Table 8: MFS_ETOPUP_ADDRESS_MASTER
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_CONFIG'', TABNAME => ''MFS_ETOPUP_ADDRESS_MASTER'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_ADDRESS_MASTER', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 9: MFS_ETOPUP_CONFIG_PARAMETERS
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_CONFIG'', TABNAME => ''MFS_ETOPUP_CONFIG_PARAMETERS'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_CONFIG_PARAMETERS', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 10: MFS_ETOPUP_ERROR_CODES
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_CONFIG'', TABNAME => ''MFS_ETOPUP_ERROR_CODES'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_ERROR_CODES', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 11: MFS_ETOPUP_LEVEL_ROLE_MENU_MAP
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_CONFIG'', TABNAME => ''MFS_ETOPUP_LEVEL_ROLE_MENU_MAP'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_LEVEL_ROLE_MENU_MAP', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 12: MFS_ETOPUP_LEVEL_MASTER
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_CONFIG'', TABNAME => ''MFS_ETOPUP_LEVEL_MASTER'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_LEVEL_MASTER', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 13: MFS_ETOPUP_ROLE_MASTER
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''CORE_CONFIG'', TABNAME => ''MFS_ETOPUP_ROLE_MASTER'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_ROLE_MASTER', CASCADE => TRUE, DEGREE => 4);
END;
/

exit SQL.SQLCODE;
