-- EREFILL Gather Stats - Schedule C Static Tables (EVENT_DATA)
-- PDB: EREFILL_EVENT (connected via ORACLE_PDB_SID)
-- Schema: EVENT_DATA
-- Non-partitioned tables that need gather stats every 12 hours

WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;

set time on
set timing on
set serveroutput on size unlimited
set feedback on

-- EVENT_DATA Schema - Non-partitioned tables (Schedule-C)
-- Table 1: MFS_P2P_TRANSACTION_01
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''EVENT_DATA'', TABNAME => ''MFS_P2P_TRANSACTION_01'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_P2P_TRANSACTION_01', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 2: MFS_P2P_TRANSACTION_02
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''EVENT_DATA'', TABNAME => ''MFS_P2P_TRANSACTION_02'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_P2P_TRANSACTION_02', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 3: MFS_ETOPUP_AUDIT_LOGS
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''EVENT_DATA'', TABNAME => ''MFS_ETOPUP_AUDIT_LOGS'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_ETOPUP_AUDIT_LOGS', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 4: MFS_ETOPUP_PSWD_HISTORY
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''EVENT_DATA'', TABNAME => ''MFS_ETOPUP_PSWD_HISTORY'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_ETOPUP_PSWD_HISTORY', CASCADE => TRUE, DEGREE => 4);
END;
/

exit SQL.SQLCODE;
