-- EREFILL Gather Stats - Schedule B
-- PDB: EREFILL_EVENT (connected via ORACLE_PDB_SID)
-- Schema: EVENT_DATA
-- Runs every 6 hours: 5,11,17,23
-- Note: MFS_ETOPUP_THRESHOLD_CHECK moved to erefill_scheduleB_core.sql


WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;

set time on

set timing on

set echo on
set termout on
set serveroutput on

-- ============================================
-- EREFILL_EVENT PDB - EVENT_DATA Schema
-- ============================================
PROMPT
PROMPT EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_CDR_01', CASCADE => TRUE, DEGREE => 4);
EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_CDR_01', CASCADE => TRUE, DEGREE => 4);
PROMPT
PROMPT EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_CDR_02', CASCADE => TRUE, DEGREE => 4);
EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_CDR_02', CASCADE => TRUE, DEGREE => 4);
PROMPT
PROMPT EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_EDR_01', CASCADE => TRUE, DEGREE => 4);
EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_EDR_01', CASCADE => TRUE, DEGREE => 4);
PROMPT
PROMPT EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_EDR_02', CASCADE => TRUE, DEGREE => 4);
EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'EVENT_DATA', TABNAME => 'MFS_EDR_02', CASCADE => TRUE, DEGREE => 4);
exit SQL.SQLCODE;
