-- EREFILL Gather Stats - Schedule A
-- PDB: EREFILL_CORE (connected via ORACLE_PDB_SID)
-- Schema: CORE_CONFIG
-- Runs every 3 hours: 2,5,8,11,14,17,20,23


WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;

set time on

set timing on

set echo on
set termout on
set serveroutput on

-- Gather stats on MFS_ETOPUP_USER_MASTER (CORE_CONFIG schema)
PROMPT
PROMPT EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_USER_MASTER', CASCADE => TRUE, DEGREE => 4);
EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'CORE_CONFIG', TABNAME => 'MFS_ETOPUP_USER_MASTER', CASCADE => TRUE, DEGREE => 4);
exit SQL.SQLCODE;
