-- create_indexes_1.sql - Index creation stream 1 (from ramram2.sql)
-- Runs in parallel with create_indexes_2.sql

--
-- TPS01_LOG_COMP_IND  (Index)
--
CREATE INDEX REPORT.TPS01_LOG_COMP_IND ON REPORT.TPS01_LOG_CARDS
(CPS01_LOGICAL_ORDER_NR, CPS01_DENOMINATION, CPS01_CURRENT_STATUS, CPS01_CARD_ID)
  TABLESPACE PPMS_INDEX_03
GLOBAL PARTITION BY HASH (CPS01_LOGICAL_ORDER_NR, CPS01_DENOMINATION, CPS01_CURRENT_STATUS, CPS01_CARD_ID) (
  PARTITION HPTPS01COMP01
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP02
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP03
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP04
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP05
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP06
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP07
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP08
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP09
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP10
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP11
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP12
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP13
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP14
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP15
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP16
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP17
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP18
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP19
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP20
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP21
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP22
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP23
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP24
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP25
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP26
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP27
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP28
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP29
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP30
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP31
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP32
    TABLESPACE PPMS_INDEX_03
)
PARALLEL ( DEGREE 30 INSTANCES 1 );




--
-- TPS01_LOG_CARD_ID_IND  (Index)
--
CREATE INDEX REPORT.TPS01_LOG_CARD_ID_IND ON REPORT.TPS01_LOG_CARDS
(CPS01_CARD_ID)
  TABLESPACE PPMS_INDEX_03
GLOBAL PARTITION BY HASH (CPS01_CARD_ID) (
  PARTITION HPTPS01CARD01
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD02
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD03
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD04
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD05
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD06
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD07
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD08
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD09
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD10
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD11
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD12
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD13
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD14
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD15
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD16
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD17
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD18
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD19
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD20
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD21
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD22
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD23
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD24
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD25
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD26
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD27
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD28
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD29
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD30
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD31
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD32
    TABLESPACE PPMS_INDEX_03
)
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS01_LOG_DATE_SOLD_IND  (Index)
--
CREATE INDEX REPORT.TPS01_LOG_DATE_SOLD_IND ON REPORT.TPS01_LOG_CARDS
(CPS01_DATE_SOLD)
  TABLESPACE PPMS_INDEX_03
GLOBAL PARTITION BY HASH (CPS01_DATE_SOLD) (
  PARTITION HPTPS01LOGDATESOLD01
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD02
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD03
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD04
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD05
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD06
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD07
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD08
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD09
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD10
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD11
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD12
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD13
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD14
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD15
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD16
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD17
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD18
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD19
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD20
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD21
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD22
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD23
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD24
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD25
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD26
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD27
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD28
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD29
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD30
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD31
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01LOGDATESOLD32
    TABLESPACE PPMS_INDEX_03
)
PARALLEL ( DEGREE 30 INSTANCES 1 );


--###############################################################



CREATE INDEX REPORT.TPS01_USED_KEY ON REPORT.TPS01_USED_CARDS
(CPS01_SERIAL_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL 30;


--
-- TPS01_USED_ORDER_DENOM_IND  (Index)
--
CREATE INDEX REPORT.TPS01_USED_ORDER_DENOM_IND ON REPORT.TPS01_USED_CARDS
(CPS01_LOGICAL_ORDER_NR, CPS01_DENOMINATION)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL 30;



--####################################################

--
-- TPS11_PK  (Index)
--
CREATE UNIQUE INDEX REPORT.TPS11_PK ON REPORT.TPS11_OUTLET_CODES
(CPS11_OUTLET_CODE)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );






--################################################################

--
-- IND_CPS30_PALLET_NUMBER  (Index)
--
CREATE INDEX REPORT.IND_CPS30_PALLET_NUMBER ON REPORT.TPS30_CARD_BOXES
(CPS30_PALLET_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- IND_CPS30_TRANSPORT_BOX  (Index)
--
CREATE INDEX REPORT.IND_CPS30_TRANSPORT_BOX ON REPORT.TPS30_CARD_BOXES
(CPS30_TRANSPORT_BOX)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS30_AVAILABLE_INDX  (Index)
--
CREATE INDEX REPORT.TPS30_AVAILABLE_INDX ON REPORT.TPS30_CARD_BOXES
(CPS30_AVAILABLE_IND)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS30_BOX_INDX  (Index)
--
CREATE INDEX REPORT.TPS30_BOX_INDX ON REPORT.TPS30_CARD_BOXES
(CPS30_BOX_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS30_DATE_INDX  (Index)
--
CREATE INDEX REPORT.TPS30_DATE_INDX ON REPORT.TPS30_CARD_BOXES
(CPS30_DATE_MODIFIED)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS30_DENOMINATION_INDX  (Index)
--
CREATE INDEX REPORT.TPS30_DENOMINATION_INDX ON REPORT.TPS30_CARD_BOXES
(CPS30_DENOMINATION_CODE)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS30_ORDER_INDX  (Index)
--
CREATE INDEX REPORT.TPS30_ORDER_INDX ON REPORT.TPS30_CARD_BOXES
(CPS30_PURCHASE_ORDER, CPS30_LINE_NUMBER, CPS30_RELEASE_NUMBER, CPS30_RECEIPT_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS30_PK  (Index)
--
CREATE UNIQUE INDEX REPORT.TPS30_PK ON REPORT.TPS30_CARD_BOXES
(CPS30_BRICK_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );




  ---#####################################

  --
  -- TPS31_ACTIVE_INDX  (Index)
  --
  CREATE INDEX REPORT.TPS31_ACTIVE_INDX ON REPORT.TPS31_CARD_BRICKS
  (CPS31_ACTIVE_IND)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );


  --
  -- TPS31_BRICK_INDX  (Index)
  --
  CREATE INDEX REPORT.TPS31_BRICK_INDX ON REPORT.TPS31_CARD_BRICKS
  (CPS31_BRICK_NUMBER)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );


  --
  -- TPS31_COMP_INDX  (Index)
  --
  CREATE INDEX REPORT.TPS31_COMP_INDX ON REPORT.TPS31_CARD_BRICKS
  (CPS31_BRICK_NUMBER, CPS31_ACTIVE_IND, CPS31_SCANNED_DATE, CPS31_EXTRACT_DATE)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );


  --
  -- TPS31_DATE_INDX  (Index)
  --
  CREATE INDEX REPORT.TPS31_DATE_INDX ON REPORT.TPS31_CARD_BRICKS
  (CPS31_DATE_MODIFIED)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );


  --
  -- TPS31_EXTRACT_INDX  (Index)
  --
  CREATE INDEX REPORT.TPS31_EXTRACT_INDX ON REPORT.TPS31_CARD_BRICKS
  (CPS31_EXTRACT_DATE)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );


  --
  -- TPS31_PK  (Index)
  --
  CREATE UNIQUE INDEX REPORT.TPS31_PK ON REPORT.TPS31_CARD_BRICKS
  (CPS31_SERIAL_NUMBER)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );


  --
  -- TPS31_SCANNED_INDX  (Index)
  --
  CREATE INDEX REPORT.TPS31_SCANNED_INDX ON REPORT.TPS31_CARD_BRICKS
  (CPS31_SCANNED_DATE)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );


  --
  -- TPS31_STOCK_FULFILL_INDX  (Index)
  --
  CREATE INDEX REPORT.TPS31_STOCK_FULFILL_INDX ON REPORT.TPS31_CARD_BRICKS
  (CPS31_STOCK_FULFILL_IND)
  NOLOGGING
  TABLESPACE PPMS_INDEX_03
  PARALLEL ( DEGREE 30 INSTANCES 1 );

 ---------------------------
CREATE INDEX REPORT.TPS08_CARD_TYPE_INDX ON REPORT.TPS08_DENOMINATION_TYPES
(CPS08_CARD_TYPE_CODE)
NOLOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );


--
-- TPS08_PK  (Index)
--
CREATE UNIQUE INDEX REPORT.TPS08_PK ON REPORT.TPS08_DENOMINATION_TYPES
(CPS08_DENOMINATION_CODE)
NOLOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );



CREATE INDEX REPORT.TPS01_LOG_USED_ORDER_DENOM_IND ON REPORT.TPS01_LOG_USED_CARDS
(CPS01_LOGICAL_ORDER_NR, CPS01_DENOMINATION)
LOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL 30;


CREATE INDEX REPORT.TPS01_LOG_USED_PKEY ON REPORT.TPS01_LOG_USED_CARDS
(CPS01_SERIAL_NUMBER)
LOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL 30;

EXIT;
