-- post_import.sql - Post-import: set index parallelism and grants
-- Run after indexes are created

-- Set all indexes to PARALLEL 2 for query execution
ALTER INDEX REPORT.TPS01_COMP_INDXN_1 PARALLEL 2;
ALTER INDEX REPORT.TPS01_PKN_1_1 PARALLEL 2;
ALTER INDEX REPORT.TPS01_BRICK_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS01_DATE_CEASED_INDX_1 PARALLEL 2;
ALTER INDEX REPORT.TPS01_CARD_ID_INDXN_1 PARALLEL 2;
ALTER INDEX REPORT.TPS01_CURSTS_INDXN PARALLEL 2;
ALTER INDEX REPORT.TPS01_DATE_SOLD_INDX_1 PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_CURSTS_IND PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_DATE_CEASED_IND PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_PKN PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_DATE_SOLD_IND PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_COMP_IND PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_CARD_ID_IND PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_USED_ORDER_DENOM_IND PARALLEL 2;
ALTER INDEX REPORT.TPS01_LOG_USED_PKEY PARALLEL 2;
ALTER INDEX REPORT.TPS01_USED_KEY PARALLEL 2;
ALTER INDEX REPORT.TPS01_USED_ORDER_DENOM_IND PARALLEL 2;
ALTER INDEX REPORT.TPS08_CARD_TYPE_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS08_PK PARALLEL 2;
ALTER INDEX REPORT.TPS09_PK PARALLEL 2;
ALTER INDEX REPORT.TPS09_LOG_PK PARALLEL 2;
ALTER INDEX REPORT.TPS107_PK PARALLEL 2;
ALTER INDEX REPORT.TPS107_UK PARALLEL 2;
ALTER INDEX REPORT.TPS11_PK PARALLEL 2;
ALTER INDEX REPORT.TPS145_ARCH_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS145_PK PARALLEL 2;
ALTER INDEX REPORT.TPS30_AVAILABLE_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS30_BOX_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS30_DATE_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS30_DENOMINATION_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS30_ORDER_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS30_PK PARALLEL 2;
ALTER INDEX REPORT.IND_CPS30_PALLET_NUMBER PARALLEL 2;
ALTER INDEX REPORT.IND_CPS30_TRANSPORT_BOX PARALLEL 2;
ALTER INDEX REPORT.TPS31_ACTIVE_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS31_BRICK_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS31_COMP_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS31_DATE_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS31_EXTRACT_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS31_PK PARALLEL 2;
ALTER INDEX REPORT.TPS31_SCANNED_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS31_STOCK_FULFILL_INDX PARALLEL 2;
ALTER INDEX REPORT.CPS6073_LOGICAL_ORDERS_PK PARALLEL 2;
ALTER INDEX REPORT.TPS73_ORDERED_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS73_PK PARALLEL 2;
ALTER INDEX REPORT.TPS73_STATUS_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS73_STEPS_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS73_TAG_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS73_TYPE_INDX PARALLEL 2;
ALTER INDEX REPORT.TPS74_PK PARALLEL 2;
ALTER INDEX REPORT.TPS74_PK1 PARALLEL 2;
ALTER INDEX REPORT.TPS74_STATUS_INDX PARALLEL 2;

-- Grants
GRANT SELECT ON REPORT.TPS01_LOG_CARDS TO AIDA_A;
GRANT SELECT ON REPORT.TPS01_CARDS TO AIDA_A;

EXIT;
