---#####################################

--
-- TPS73_ORDERED_INDX  (Index)
--
CREATE INDEX REPORT.TPS73_ORDERED_INDX ON REPORT.TPS73_LOGICAL_ORDERS
(CPS73_DATE_ORDERED)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS73_PK  (Index)
--
CREATE UNIQUE INDEX REPORT.TPS73_PK ON REPORT.TPS73_LOGICAL_ORDERS
(CPS73_ORDER_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS73_STATUS_INDX  (Index)
--
CREATE INDEX REPORT.TPS73_STATUS_INDX ON REPORT.TPS73_LOGICAL_ORDERS
(CPS73_STATUS)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS73_STEPS_INDX  (Index)
--
CREATE INDEX REPORT.TPS73_STEPS_INDX ON REPORT.TPS73_LOGICAL_ORDERS
(CPS73_STEPS)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS73_TAG_INDX  (Index)
--
CREATE INDEX REPORT.TPS73_TAG_INDX ON REPORT.TPS73_LOGICAL_ORDERS
(CPS73_OPTIMIZE_TAG)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS73_TYPE_INDX  (Index)
--
CREATE INDEX REPORT.TPS73_TYPE_INDX ON REPORT.TPS73_LOGICAL_ORDERS
(CPS73_ORDER_TYPE)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );




---#####################################

CREATE UNIQUE INDEX REPORT.TPS107_PK ON REPORT.TPS107_DISTRIBUTOR_DETAILS
(CPS107_DISTRIBUTOR_CODE)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS107_UK  (Index)
--
CREATE UNIQUE INDEX REPORT.TPS107_UK ON REPORT.TPS107_DISTRIBUTOR_DETAILS
(CPS107_DISTRIBUTOR)
NOLOGGING
TABLESPACE PPMS_INDEX_04
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
----########################################



-- TPS01_CURSTS_INDXN  (Index)
--
CREATE INDEX REPORT.TPS01_CURSTS_INDXN ON REPORT.TPS01_CARDS
(CPS01_CURRENT_STATUS)
LOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 30 INSTANCES 1 );


--
-- TPS01_DATE_CEASED_INDX_1  (Index)
--
CREATE INDEX REPORT.TPS01_DATE_CEASED_INDX_1 ON REPORT.TPS01_CARDS
(CPS01_DATE_CEASED)
LOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 30 INSTANCES 1 );



--
-- TPS01_CARD_ID_INDXN_1  (Index)
--
CREATE  INDEX REPORT.TPS01_CARD_ID_INDXN_1 ON REPORT.TPS01_CARDS
(CPS01_CARD_ID)
  TABLESPACE PPMS_INDEX_03
GLOBAL PARTITION BY HASH (CPS01_CARD_ID) (
  PARTITION HPTPS01CARD01
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD02
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD03
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD04
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD05
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD06
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD07
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD08
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD09
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD10
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD11
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD12
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD13
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD14
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD15
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD16
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD17
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD18
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD19
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD20
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD21
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD22
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD23
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD24
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD25
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD26
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD27
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD28
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD29
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD30
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD31
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01CARD32
    TABLESPACE PPMS_INDEX_03
)
PARALLEL ( DEGREE 30 INSTANCES 1 );






CREATE INDEX REPORT.TPS01_DATE_SOLD_INDX_1 ON REPORT.TPS01_CARDS
(CPS01_DATE_SOLD)
  TABLESPACE PPMS_INDEX_03
GLOBAL PARTITION BY HASH (CPS01_DATE_SOLD) (
  PARTITION HPTPS01DATESOLD01
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD02
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD03
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD04
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD05
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD06
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD07
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD08
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD09
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD10
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD11
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD12
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD13
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD14
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD15
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD16
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD17
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD18
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD19
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD20
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD21
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD22
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD23
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD24
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD25
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD26
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD27
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD28
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD29
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD30
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD31
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01DATESOLD32
    TABLESPACE PPMS_INDEX_03
)
PARALLEL ( DEGREE 30 INSTANCES 1 );






--
-- TPS01_COMP_INDXN_1  (Index)
--
CREATE INDEX REPORT.TPS01_COMP_INDXN_1 ON REPORT.TPS01_CARDS
(CPS01_LOGICAL_ORDER_NR, CPS01_DENOMINATION, CPS01_CURRENT_STATUS, CPS01_CARD_ID)
  TABLESPACE PPMS_INDEX_03
GLOBAL PARTITION BY HASH (CPS01_LOGICAL_ORDER_NR, CPS01_DENOMINATION, CPS01_CURRENT_STATUS, CPS01_CARD_ID) (
  PARTITION HPTPS01COMP01
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP02
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP03
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP04
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP05
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP06
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP07
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP08
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP09
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP10
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP11
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP12
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP13
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP14
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP15
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP16
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP17
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP18
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP19
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP20
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP21
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP22
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP23
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP24
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP25
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP26
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP27
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP28
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP29
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP30
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP31
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01COMP32
    TABLESPACE PPMS_INDEX_03
)
PARALLEL ( DEGREE 30 INSTANCES 1 );




CREATE  INDEX REPORT.TPS01_PKN_1_1 ON REPORT.TPS01_CARDS
(CPS01_SERIAL_NUMBER)
  TABLESPACE PPMS_INDEX_03
GLOBAL PARTITION BY HASH (CPS01_SERIAL_NUMBER) (
  PARTITION HPTPS01PKN01
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN02
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN03
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN04
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN05
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN06
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN07
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN08
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN09
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN10
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN11
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN12
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN13
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN14
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN15
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN16
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN17
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN18
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN19
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN20
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN21
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN22
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN23
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN24
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN25
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN26
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN27
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN28
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN29
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN30
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN31
    TABLESPACE PPMS_INDEX_03,
  PARTITION HPTPS01PKN32
    TABLESPACE PPMS_INDEX_03
)
PARALLEL ( DEGREE 30 INSTANCES 1 );



-
-- TPS01_LOG_CURSTS_IND  (Index)
--
CREATE INDEX REPORT.TPS01_LOG_CURSTS_IND ON REPORT.TPS01_LOG_CARDS
(CPS01_CURRENT_STATUS)
LOGGING
TABLESPACE PPMS_INDEX_03
parallel 30;


--
-- TPS01_LOG_DATE_CEASED_IND  (Index)
--
CREATE INDEX REPORT.TPS01_LOG_DATE_CEASED_IND ON REPORT.TPS01_LOG_CARDS
(CPS01_DATE_CEASED)
LOGGING
TABLESPACE PPMS_INDEX_03
parallel 30;


              --
              CREATE  INDEX REPORT.TPS01_LOG_PKN ON REPORT.TPS01_LOG_CARDS
              (CPS01_SERIAL_NUMBER)
                TABLESPACE PPMS_INDEX_03
              GLOBAL PARTITION BY HASH (CPS01_SERIAL_NUMBER) (
                PARTITION LOGHPTPS01PKN01
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN02
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN03
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN04
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN05
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN06
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN07
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN08
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN09
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN10
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN11
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN12
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN13
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN14
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN15
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN16
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN17
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN18
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN19
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN20
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN21
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN22
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN23
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN24
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN25
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN26
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN27
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN28
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN29
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN30
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN31
                  TABLESPACE PPMS_INDEX_03,
                PARTITION LOGHPTPS01PKN32
                  TABLESPACE PPMS_INDEX_03
              )
              PARALLEL ( DEGREE 30 INSTANCES 1 );


CREATE INDEX REPORT.TPS01_BRICK_INDX ON REPORT.TPS01_CARDS
(CPS01_BRICK_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 30 INSTANCES 1 );


CREATE UNIQUE INDEX REPORT.CPS6073_LOGICAL_ORDERS_PK ON REPORT.TPS6073_LOGICAL_ORDERS
(CPS6073_ORDER_NUMBER)
LOGGING
TABLESPACE PPMS_DATA_04
NOPARALLEL;



CREATE INDEX REPORT.TPS09_LOG_PK ON REPORT.TPS09_PPAS_LOG_CARD_PARAMETERS
(CPS09_CARD_TYPE_CODE)
LOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );


COMMENT ON COLUMN REPORT.TPS09_PPAS_CARD_PARAMETERS.CPS09_VS_CARD_TYPE_CODE IS '''V'' - Physical Voucher
''W'' - Wimax voucher
''L'' - Logical Voucher';


CREATE INDEX REPORT.TPS09_PK ON REPORT.TPS09_PPAS_CARD_PARAMETERS
(CPS09_CARD_TYPE_CODE)
NOLOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );


CREATE INDEX REPORT.TPS145_ARCH_INDX ON REPORT.TPS145_STOCK_ORDERS
(CPS145_OPTIMIZE_TAG)
NOLOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );


CREATE INDEX REPORT.TPS145_PK ON REPORT.TPS145_STOCK_ORDERS
(CPS145_STOCK_NUMBER, CPS145_ORDER_NUMBER, CPS145_LINE_NUMBER, CPS145_RELEASE_NUMBER, CPS145_LINE_ITEM_NUMBER,
CPS145_DELIVERY_NUMBER)
NOLOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );

CREATE INDEX REPORT.TPS74_PK ON REPORT.TPS74_LOGICAL_ORDERS_DETAIL
(CPS74_ORDER_NUMBER, CPS74_DENOMINATION)
LOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );


CREATE INDEX REPORT.TPS74_PK1 ON REPORT.TPS74_LOGICAL_ORDERS_DETAIL
(CPS74_ORDER_NUMBER, CPS74_LINE_NO, CPS74_REL_NO)
LOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );


CREATE INDEX REPORT.TPS74_STATUS_INDX ON REPORT.TPS74_LOGICAL_ORDERS_DETAIL
(CPS74_STATUS)
NOLOGGING
TABLESPACE PPMS_INDEX_03
PARALLEL ( DEGREE 12 INSTANCES 1 );
