-- Oracle DDL Script for Database Size Collector
-- Run this as the dba_db_size user or with appropriate privileges
-- Schema: dba_db_size

-- ============================================================
-- Oracle Database Sizes Table
-- ============================================================
CREATE TABLE oracle_db_sizes (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date     DATE NOT NULL,
    hostname            VARCHAR2(100) NOT NULL,
    ip_address          VARCHAR2(45),
    instance_name       VARCHAR2(100),
    db_name             VARCHAR2(100),
    physical_size_gb    NUMBER(12,2),  -- datafile + tempfile + redo (100GB buffer)
    logical_size_gb     NUMBER(12,2),  -- dba_segments actual data
    application         VARCHAR2(200),
    environment         VARCHAR2(50),
    db_version          VARCHAR2(50),
    collection_status   VARCHAR2(20) DEFAULT 'SUCCESS',  -- SUCCESS, FAILED, PARTIAL
    error_message       VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_oracle_sizes_date ON oracle_db_sizes(collection_date);
CREATE INDEX idx_oracle_sizes_host ON oracle_db_sizes(hostname, instance_name);

-- ============================================================
-- MySQL Database Sizes Table
-- ============================================================
CREATE TABLE mysql_db_sizes (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date     DATE NOT NULL,
    hostname            VARCHAR2(100) NOT NULL,
    ip_address          VARCHAR2(45),
    port                NUMBER(5),
    physical_size_gb    NUMBER(12,2),  -- du on data + binlog directories
    logical_size_gb     NUMBER(12,2),  -- information_schema.tables sum
    application         VARCHAR2(200),
    environment         VARCHAR2(50),
    db_version          VARCHAR2(50),
    role                VARCHAR2(50),  -- Master/Slave/Standalone
    collection_status   VARCHAR2(20) DEFAULT 'SUCCESS',
    error_message       VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_mysql_sizes_date ON mysql_db_sizes(collection_date);
CREATE INDEX idx_mysql_sizes_host ON mysql_db_sizes(hostname, port);

-- ============================================================
-- MongoDB Database Sizes Table
-- ============================================================
CREATE TABLE mongo_db_sizes (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date     DATE NOT NULL,
    hostname            VARCHAR2(100) NOT NULL,
    ip_address          VARCHAR2(45),
    port                NUMBER(5),
    physical_size_gb    NUMBER(12,2),  -- du on data directory
    logical_size_gb     NUMBER(12,2),  -- db.stats() dataSize
    replicaset_name     VARCHAR2(100),
    role                VARCHAR2(50),  -- primary/secondary/arbiter
    application         VARCHAR2(200),
    environment         VARCHAR2(50),
    db_version          VARCHAR2(50),
    collection_status   VARCHAR2(20) DEFAULT 'SUCCESS',
    error_message       VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_mongo_sizes_date ON mongo_db_sizes(collection_date);
CREATE INDEX idx_mongo_sizes_host ON mongo_db_sizes(hostname, port);

-- ============================================================
-- PostgreSQL Database Sizes Table
-- ============================================================
CREATE TABLE postgres_db_sizes (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date     DATE NOT NULL,
    hostname            VARCHAR2(100) NOT NULL,
    ip_address          VARCHAR2(45),
    port                NUMBER(5),
    physical_size_gb    NUMBER(12,2),  -- du on data directory
    logical_size_gb     NUMBER(12,2),  -- pg_database_size sum
    role                VARCHAR2(50),  -- Primary/Secondary/Standalone
    application         VARCHAR2(200),
    environment         VARCHAR2(50),
    db_version          VARCHAR2(50),
    collection_status   VARCHAR2(20) DEFAULT 'SUCCESS',
    error_message       VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_postgres_sizes_date ON postgres_db_sizes(collection_date);
CREATE INDEX idx_postgres_sizes_host ON postgres_db_sizes(hostname, port);

-- ============================================================
-- Cassandra Database Sizes Table (Physical only)
-- ============================================================
CREATE TABLE cassandra_db_sizes (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date     DATE NOT NULL,
    hostname            VARCHAR2(100) NOT NULL,
    ip_address          VARCHAR2(45),
    port                NUMBER(5),
    physical_size_gb    NUMBER(12,2),  -- du on data directory
    cluster_name        VARCHAR2(100),
    datacenter          VARCHAR2(100),
    application         VARCHAR2(200),
    environment         VARCHAR2(50),
    db_version          VARCHAR2(50),
    collection_status   VARCHAR2(20) DEFAULT 'SUCCESS',
    error_message       VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_cassandra_sizes_date ON cassandra_db_sizes(collection_date);
CREATE INDEX idx_cassandra_sizes_host ON cassandra_db_sizes(hostname);

-- ============================================================
-- SQL Server Database Sizes Table (Placeholder)
-- ============================================================
CREATE TABLE mssql_db_sizes (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date     DATE NOT NULL,
    hostname            VARCHAR2(100) NOT NULL,
    ip_address          VARCHAR2(45),
    port                NUMBER(5),
    physical_size_gb    NUMBER(12,2),
    logical_size_gb     NUMBER(12,2),
    instance_name       VARCHAR2(100),
    application         VARCHAR2(200),
    environment         VARCHAR2(50),
    db_version          VARCHAR2(50),
    collection_status   VARCHAR2(20) DEFAULT 'SUCCESS',
    error_message       VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_mssql_sizes_date ON mssql_db_sizes(collection_date);
CREATE INDEX idx_mssql_sizes_host ON mssql_db_sizes(hostname, port);

-- ============================================================
-- Collection Summary Table (for monitoring)
-- ============================================================
CREATE TABLE collection_summary (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date     DATE NOT NULL,
    platform            VARCHAR2(20) NOT NULL,  -- oracle, mysql, mongo, postgres, cassandra, mssql
    total_hosts         NUMBER(5),
    successful_hosts    NUMBER(5),
    failed_hosts        NUMBER(5),
    total_physical_gb   NUMBER(14,2),
    total_logical_gb    NUMBER(14,2),
    start_time          TIMESTAMP,
    end_time            TIMESTAMP,
    duration_seconds    NUMBER(8,2),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_collection_summary_date ON collection_summary(collection_date, platform);

-- ============================================================
-- Views for easy reporting
-- ============================================================

-- Daily total sizes by platform
CREATE OR REPLACE VIEW v_daily_db_sizes AS
SELECT 
    collection_date,
    platform,
    SUM(total_physical_gb) AS physical_gb,
    SUM(total_logical_gb) AS logical_gb
FROM collection_summary
GROUP BY collection_date, platform
ORDER BY collection_date DESC, platform;

-- Latest sizes per host (Oracle)
CREATE OR REPLACE VIEW v_latest_oracle_sizes AS
SELECT * FROM (
    SELECT 
        hostname,
        instance_name,
        ip_address,
        physical_size_gb,
        logical_size_gb,
        application,
        collection_date,
        ROW_NUMBER() OVER (PARTITION BY hostname, instance_name ORDER BY collection_date DESC) AS rn
    FROM oracle_db_sizes
    WHERE collection_status = 'SUCCESS'
)
WHERE rn = 1;

-- Latest sizes per host (MySQL)
CREATE OR REPLACE VIEW v_latest_mysql_sizes AS
SELECT * FROM (
    SELECT 
        hostname,
        port,
        ip_address,
        physical_size_gb,
        logical_size_gb,
        application,
        role,
        collection_date,
        ROW_NUMBER() OVER (PARTITION BY hostname, port ORDER BY collection_date DESC) AS rn
    FROM mysql_db_sizes
    WHERE collection_status = 'SUCCESS'
)
WHERE rn = 1;

-- Weekly growth report
CREATE OR REPLACE VIEW v_weekly_growth AS
SELECT 
    platform,
    TRUNC(collection_date, 'IW') AS week_start,
    MAX(total_physical_gb) - MIN(total_physical_gb) AS physical_growth_gb,
    MAX(total_logical_gb) - MIN(total_logical_gb) AS logical_growth_gb
FROM collection_summary
WHERE collection_date >= TRUNC(SYSDATE) - 90
GROUP BY platform, TRUNC(collection_date, 'IW')
ORDER BY week_start DESC, platform;

-- Grant permissions (if needed)
-- GRANT SELECT ON v_daily_db_sizes TO <monitoring_user>;
-- GRANT SELECT ON v_latest_oracle_sizes TO <monitoring_user>;
-- GRANT SELECT ON v_latest_mysql_sizes TO <monitoring_user>;
-- GRANT SELECT ON v_weekly_growth TO <monitoring_user>;

COMMIT;

-- Verification
SELECT table_name FROM user_tables WHERE table_name LIKE '%_SIZES' OR table_name = 'COLLECTION_SUMMARY';
SELECT view_name FROM user_views WHERE view_name LIKE 'V_%';
