-- MFS_REPORT Gather Stats - Schedule C Static Tables
-- Server: Drl168
-- PDB: MFS_REPORT (connected via ORACLE_PDB_SID)
-- Schema: APP_USER
-- Non-partitioned tables that need gather stats every 12 hours

WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;

set time on
set timing on
set serveroutput on size unlimited
set feedback on

-- APP_USER Schema - Non-partitioned tables (Schedule-C)
-- Table 1: MFS_RPT_FACT
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''APP_USER'', TABNAME => ''MFS_RPT_FACT'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'APP_USER', TABNAME => 'MFS_RPT_FACT', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 2: MFS_RPT_SERVICE_FACT
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''APP_USER'', TABNAME => ''MFS_RPT_SERVICE_FACT'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'APP_USER', TABNAME => 'MFS_RPT_SERVICE_FACT', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 3: MFS_RPT_RECON_FACT
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''APP_USER'', TABNAME => ''MFS_RPT_RECON_FACT'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'APP_USER', TABNAME => 'MFS_RPT_RECON_FACT', CASCADE => TRUE, DEGREE => 4);
END;
/

-- Table 4: MFS_RPT_HOURLY_FACT
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> ''APP_USER'', TABNAME => ''MFS_RPT_HOURLY_FACT'', CASCADE => TRUE, DEGREE => 4);');
    DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=> 'APP_USER', TABNAME => 'MFS_RPT_HOURLY_FACT', CASCADE => TRUE, DEGREE => 4);
END;
/

exit SQL.SQLCODE;
